version: "2"
services:
  server:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  client:
    build: 
      context: .
      dockerfile: Dockerfile-client
    ports:
      - "3001:3001"
    depends_on: 
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"    